services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_php
        volumes:
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
